#!/bin/bash
set -e

echo "🚀 [Secreton] iOS script phase running..."

WORKSPACE_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
ENVFILE="${ENVFILE:-.env}"
CLI_BIN="$WORKSPACE_ROOT/node_modules/.bin/rn-secreton-cli"
GENERATED_FILE="$WORKSPACE_ROOT/Secreton.xcconfig"

if [ ! -f "$WORKSPACE_ROOT/$ENVFILE" ]; then
  echo "❌ ENV file not found: $WORKSPACE_ROOT/$ENVFILE"
  exit 1
fi

if [ ! -f "$CLI_BIN" ]; then
  echo "❌ rn-secreton-cli not found at $CLI_BIN"
  exit 1
fi

echo "🔐 rn-secreton generating env (iOS)..."
: "${ENV_SECRET_KEY:?❌ ENV_SECRET_KEY not set}"

"$CLI_BIN" "$WORKSPACE_ROOT/$ENVFILE" --out "$GENERATED_FILE"

if [ ! -f "$GENERATED_FILE" ]; then
  echo "// Generated by rn-secreton-cli" > "$GENERATED_FILE"
  while IFS='=' read -r key value; do
    [ -z "$key" ] && continue
    [[ "$key" =~ ^# ]] && continue
    echo "$key=$value" >> "$GENERATED_FILE"
  done < "$WORKSPACE_ROOT/$ENVFILE"
fi

echo "✅ Secreton.xcconfig generated at $GENERATED_FILE"
