#!/bin/bash
set -e

echo "🚀 [Secreton] iOS script phase running..."

WORKSPACE_ROOT="${SRCROOT}/../.."
ENVFILE="${ENVFILE:-.env}"

ENV_PATH="$WORKSPACE_ROOT/$ENVFILE"
CLI_BIN="$WORKSPACE_ROOT/node_modules/.bin/rn-secreton-cli"
GENERATED_FILE="$WORKSPACE_ROOT/ios/Secreton.xcconfig"

echo "📁 WORKSPACE_ROOT = $WORKSPACE_ROOT"
echo "📄 ENVFILE = $ENV_PATH"

if [ ! -f "$ENV_PATH" ]; then
  echo "❌ ENV file not found: $ENV_PATH"
  exit 1
fi

echo "📄 Loading env vars"
set -a
source "$ENV_PATH"
set +a

: "${ENV_SECRET_KEY:?❌ ENV_SECRET_KEY not set in $ENVFILE}"

if [ ! -f "$CLI_BIN" ]; then
  echo "❌ rn-secreton-cli not found at $CLI_BIN"
  exit 1
fi

echo "🔐 rn-secreton generating env (iOS)..."
"$CLI_BIN" "$ENV_PATH" --out "$GENERATED_FILE"

touch "$GENERATED_FILE"

echo "// Generated by rn-secreton-cli" > "$GENERATED_FILE"
while IFS='=' read -r key value || [ -n "$key" ]; do
  [[ -z "$key" ]] && continue
  [[ "$key" =~ ^# ]] && continue

  if ! grep -q "^${key}=" "$GENERATED_FILE"; then
    echo "➕ adding missing key: $key"
    echo "$key=$value" >> "$GENERATED_FILE"
  fi
done < "$ENV_PATH"

echo "✅ Secreton.xcconfig generated at $GENERATED_FILE"
